title: Patagon
logo: /assets/images/logo.png
email: hola@patagon.dev
motto: Patagon projects rocks 🎸!
description: >- # this means to ignore newlines until "baseurl:"
  A full stack Marketplace solution with all the stuff you need.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  matrix:
    output: false
  compare:
    output: true
  compares_data:
    output: false
permalink: pretty

# Build settings
# plugins:
#   - jekyll-feed
exclude:
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
