title: Patagon Consulting
logo: /assets/images/logo.png
email: hola@patagon.dev
motto: Patagon projects rocks 🎸!
description: >- # this means to ignore newlines until "baseurl:"
  Ayudamos a nuestros clientes a capturar todo el valor de sus inversiones en tecnología, promoviendo y capacitando las mejores prácticas de la industria que revolucionarán su forma de trabajar
baseurl: ""
url: ""
collections:
  matrix:
    output: false
  compare:
    output: true
  compares_data:
    output: false
permalink: pretty

# Build settings
# plugins:
#   - jekyll-feed
exclude:
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
