backend:
  name: github
  repo: nmella/mercadostack
#  name: git-gateway
  branch: master # 
media_folder: assets/images/
public_folder: assets/images/
publish_mode: editorial_workflow
collections:
# common pages parts
  - label: Common parts
    name: parts
    files:
# top navigation menu
      - name: navigation
        label: Top navigation menu
        file: _data/navigation.yml
        fields:
        - label: Navigation items
          name: items
          widget: list
          fields:
          - label: title,
            name: title
            widget: string
          - label: link
            name: link
            widget: string
            default: "#"
# contact form
      - name: contact_form
        label: Contact Form
        file: _data/contact_form.yml
        fields:
          - label: inputs
            name: inputs
            widget: list
            fields:
            - label: name
              name: name
              widget: string
            - label: caption
              name: caption
              widget: string
            - label: placeholder
              name: placeholder
              widget: string
            - label: required
              name: required
              widget: string
            - label: type
              name: type
              widget: string
            - label: order
              name: order
              widget: string
          - label: textarea
            name: textarea
            widget: object
            fields:
            - label: caption
              name: caption
              widget: string
            - label: placeholder
              name: placeholder
              widget: string
            - label: name
              name: name
              widget: string
            - label: rows
              name: rows
              widget: number
          - label: button
            name: button
            widget: string
          - label: site_key
            name: site_key
            widget: string
              

# call yo action
      - name: CTA
        label: Call to action
        file: _data/cta.yml
        fields:
          - label: small
            name: small
            widget: string
          - label: span
            name: span
            widget: string
          - label: title
            name: title
            widget: string
          - label: link
            name: link
            widget: string
            default: "#"
          - label: image
            name: image
            widget: image
            default: /assets/images/cta.png
          - label: l_title
            name: l_title
            widget: string
# footer
      - name: footer
        label: Footer
        file:  _data/footer.yml
        fields:
        - name: top
          label: Footer top
          widget: list
          fields:
            - name: title
              label: Column Title
              widget: string
            - name: items
              label: Items
              widget: list
              fields:
                - name: name_c
                  label: Name
                  widget: string
                - name: link
                  label: Link
                  widget: string
        - name: social
          label: Social
          widget: list
          fields:
            - name: icon
              label: Icon
              widget: string
            - name: title
              label: title
              widget: string
            - name: link
              label: link
              widget: string

# homepage
  - label: MercadoStack home page
    name: homepage
    files:

      - name: home_mosaic
        label: home mosaic
        file: _data/home.yml
        fields:

        - label: Mosaic title
          name: 'mosaic_title'
          widget: 'string'
          default: 

        - label: Mosaic description
          name: 'mosaic_descr'
          widget: 'string'
          default: 
          required: false

        - label: Mosaic link
          name: 'mosaic_link'
          widget: 'string'
          default: 
          required: false

        - label: Mosaic text
          name: 'mosaic_text'
          widget: 'string'
          default: 
          required: false

        - label: Mosaic table
          name: 'mosaic'
          widget: 'list'
          fields:
            - label: Row
              name: row
              widget: list
              fields: 
                - label: Title
                  name: title
                  widget: string
                - label: link
                  name: link
                  widget: string
                  default: "#"
                - label: description
                  name: descr
                  widget: string
                - label: image
                  name: image
                  widget: string

# compare pages
  - name: compare
    label: compare pages data
    folder: /_compare/
    create: true
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: description
        name: description
        widget: string
        required: false
      - label: table_head1
        name: table_head1
        widget: string
        required: false
      - label: table_head2
        name: table_head2
        widget: string
        required: false

      - label: compare table
        name: compare_table
        widget: list
        fields: 
          - name: title
            title: title
            widget: string
          - name: val1
            title: val1
            widget: string
            default: "No"
          - name: val2
            title: val2
            widget: string
            default: "Yes"
          - name: class1
            title: class1
            widget: string
          - name: class2
            title: class2
            widget: string

      - name: links
        label: links
        widget: list
        fields:
          - name: title
            label: title
            widget: string
          - name: link
            label: link
            widget: string
      - name: body
        label: body
        widget: markdown
        required: false

# prices page
  - name: prices
    label: prices
    files:
    - file: _data/prices.yml
      name: prices
      label: prices
      media_folder: /assets/images/
      fields:
      - name: free
        label: free plan
        widget: object
        fields: 
          - name: title
            label: title
            widget: string
          - name: descr
            label: descr
            widget: text
          - name: span
            label: span
            widget: string
          - name: image
            label: image
            widget: string
          - name: features
            label: features
            widget: object
            fields:
              - name: title
                label: title
                widget: string
              - name: link
                label: link
                widget: string
              - label: button
                name: button
                widget: object
                fields: 
                  - name: title
                    label: title
                    widget: string
                  - name: link
                    label: link
                    widget: string
                  - name: color
                    label: color
                    widget: string
                    required: false
              - label: after
                name: after
                widget: object
                required: false
                fields: 
                  - name: title
                    label: title
                    widget: string
                  - name: link
                    label: link
                    widget: string
                  - name: text
                    label: text
                    widget: string
              - label: list
                name: list
                widget: list
                fields:
                - name: item
                  label: item
                  widget: string

      - name: hiperlinks
        label: hiperlinks
        widget: list
        fields: 
          - name: title
            label: title
            widget: string
          - name: link
            label: link
            widget: string

      - name: premium
        label: Premium plans
        widget: object
        fields:

          - name: title
            label: title
            widget: string
          - name: descr
            label: descr
            widget: text
          - name: plans
            label: plans
            widget: list
            fields:

            - name: item
              label: item
              widget: object
              fields:

              - name: name
                label: name
                widget: string

              - name: items
                label: items
                widget: list
                fields:

                - name: title
                  label: title
                  widget: string
                - name: descr
                  label: descr
                  widget: string
                - name: price-p
                  label: price-p
                  widget: string
                - name: price-s
                  label: price-s
                  widget: string
                - name: features
                  label: features
                  widget: object
                  fields:
                  
                  - name: title
                    label: title
                    widget: string

                  - name: link
                    label: link
                    widget: string

                  - name: button
                    label: button
                    widget: object
                    fields:
                  
                    - name: title
                      label: title
                      widget: string
  
                    - name: link
                      label: link
                      widget: string
  
                    - name: color
                      label: color
                      widget: string
                      required: false

                  - name: list
                    label: list
                    widget: list
                    fields:
                  
                    - name: item
                      label: item
                      widget: string

# features page
  - name: features-matrix
    label: features matrix
    files:
    - file: /_data/matrix.yml
      name: matrix
      label: matrix
      media_folder: /assets/images/
      fields:
      - name: feature_image
        label: image
        widget: string
      - name: tip
        label: tip
        widget: string
      - name: cards
        label: cards
        widget: list
        fields: 
          - name: title
            label: title
            widget: string
          - name: text
            label: text
            widget: string
          - name: link
            label: link
            widget: string
          - name: headline
            label: headline
            widget: string
      - name: cta
        label: call to actions
        widget: list
        fields:
          - name: title
            label: title
            widget: string
          - name: link
            label: link
            widget: string
      - name: matrix
        label: matrix tables list
        widget: list
        fields:
          - name: title
            label: title
            widget: string
          - name: table
            label: table number
            widget: string

  - name: features-table-1
    label: features table 1
    folder: /_matrix/table-01/
    create: true
    media_folder: /assets/images/
    fields:
      - name: table
        label: features table number
        widget: string
      - name: title
        label: table-row-col
        widget: string
        required: false
      - name: body
        label: body
        widget: markdown
        required: false
  - name: features-table-2
    label: features table 2
    folder: /_matrix/table-02/
    create: true
    media_folder: /assets/images/
    fields:
      - name: table
        label: features table number
        widget: string
      - name: title
        label: table-row-col
        widget: string
        required: false
      - name: body
        label: body
        widget: markdown
        required: false
  - name: features-table-3
    label: features table 3
    folder: /_matrix/table-03/
    create: true
    media_folder: /assets/images/
    fields:
      - name: table
        label: features table number
        widget: string
      - name: title
        label: table-row-col
        widget: string
        required: false
      - name: body
        label: body
        widget: markdown
        required: false
  - name: features-table-4
    label: features table 4
    folder: /_matrix/table-04/
    create: true
    media_folder: /assets/images/
    fields:
      - name: table
        label: features table number
        widget: string
      - name: title
        label: table-row-col
        widget: string
        required: false
      - name: body
        label: body
        widget: markdown
        required: false

# posts
  - name: posts
    label: Posts
    folder: /_posts/
    create: true
    media_folder: /assets/images/
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: image,          name: image,       widget: image, required: false }
      - { label: description,    name: description, widget: string, default: , required: false }
      - { label: slug,           name: slug,        widget: string, required: false }
      - { label: Layout,         name: layout,      widget: string, default: post }
      - { label: Title,          name: title,       widget: string }
      - { label: Publish Date,   name: date,        widget: date, format: YYYY-MM-DD }
      - { label: Tags,           name: tags,        widget: string, required: false }
      - { label: Allow comments, name: comments,    widget: boolean, required: false, default: true }
      - { label: Body,           name: body,        widget: markdown, required: false }

# pages
  - name: pages
    label: Pages
    folder: "./"
    create: true
    media_folder: /assets/images/
    fields:
      - { label: image,          name: image,       widget: image, required: false }
      - { label: description,    name: description, widget: string, default: , required: false }
      - { label: slug,           name: slug,        widget: string, required: false }
      - { label: Layout,         name: layout,      widget: string, default: default }
      - { label: Title,          name: title,       widget: string }
      - { label: Publish Date,   name: date,        widget: date, format: YYYY-MM-DD, required: false }
      - { label: Tags,           name: tags,        widget: string, required: false }
      - { label: Body,           name: body,        widget: markdown, required: false }
